# Generated by Django 4.2.1 on 2023-06-14 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('Doctor', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='users.doctors'),
        ),
    ]
