# Generated by Django 4.2.1 on 2023-06-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0004_slot_doctor'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patients')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.slot')),
            ],
        ),
    ]
