# Generated by Django 4.2.1 on 2023-06-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='doctors',
            new_name='doctor',
        ),
    ]
