# Generated by Django 4.2.1 on 2023-06-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_rename_doctors_bookings_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
            ],
        ),
    ]
