# Generated by Django 4.2.1 on 2023-06-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_patient_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='patient_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Booking.patient_details'),
            preserve_default=False,
        ),
    ]
